version: "3"
include: 
  - proxy.yaml
services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile.python
    networks:
        backend: 
          ipv4_address: 172.20.0.5
    environment:
     - DB_HOST = 172.20.0.10
     - DB_USER = app
     - DB_PASSWORD = QwErTy1234
     - DB_NAME = virtd
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
  db:
    image: mysql:8
    environment:
     - MYSQL_ROOT_PASSWORD = 12345
     - MYSQL_DATABASE = virtd
     - MYSQL_USER = app
     - MYSQL_PASSWORD = QwErTy1234
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.10

networks:
  backend: 
    driver: bridge
    ipam:
        config:
        - subnet: 172.20.0.0/24
