version: "3"
include: 
  - proxy.yaml
services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile.python
    networks:
      - new
    ports:
      - 172.20.0.5:5000:5000
    deploy:
      restart_policy:
        condition: on-failure
  db:
    image: image=mysql:8
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_USER==${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    networks:
      - new
    ports:
        - 172.20.0.10:3306:3306

  networks:
    new: 
      driver: bridge
      ipam:
         config:
          - subnet: 172.20.0.0/24
