version: "3"
include: 
  - proxy.yaml
services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile.python
    networks:
        backend: {}
        vpcbr:
          ipv4_address: 172.20.0.5
    environment:
     - DB_HOST = 172.20.0.10:3306
     - DB_USER=${MYSQL_USER}
     - DB_PASSWORD==${MYSQL_PASSWORD}
     - DB_NAME=${MYSQL_DATABASE}
    deploy:
      restart_policy:
        condition: on-failure
  db:
    image: mysql:8
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_USER==${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    networks:
        backend: {}
        vpcbr:
          ipv4_address: 172.20.0.10

networks:
  backend: 
    driver: bridge
    ipam:
        config:
        - subnet: 172.20.0.0/24
